### PR TITLE
Automatically set the GVSP Packet size.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
This is necessary at least for the G-046C, and it's being done by the
API examples, too. Without it, the node receives frames which don't fail but have 0 data size.

### CODE REVIEW

**Comment by miquelmassot** [comment]
Hi @lucasb-eyer, thanks for the contribution! Right now I'm restructuring the package in order to accomodate stereo-capable avt cameras and (hopefully) I'll finish coding soon. I'll try to integrate your modifications ASAP.

**Comment by lucasb-eyer** [comment]
Hi, no stress, it's not urgent to me since we can use my fork in the meantime, just wanted to share and potentially save others days of debugging :)

**Comment by lucasb-eyer** [comment]
sorry for the noise, had a little fight with git :-/

**Comment by miquelmassot** [comment]
I'll to some tests on this issue. If there's only one camera the adjustment may be fine, but if there are more than one cameras, we may need to adjust it manually.

Don't worry for the noise. Hit harder ;-)

**Comment by miquelmassot** [comment]
You could simplify it by:

```
if ( cam_int_type == VmbInterfaceEthernet ){
  runCommand("GVSPAdjustPacketSize")
}
```

**Comment by lucasb-eyer** [comment]
Fixed the merge conflict, will look at your suggestion.

I also feared the two-camera thing, but we are currently using this as-is with two cameras and it (seems to) work fine. The two cameras and the laptop are all connected by a switch. Is there some test you want me to run in order to verify?

**Comment by miquelmassot** [comment]
I may be interested in you setup. Are you syncing the cameras? I'm trying to set a stereo pair.

**Comment by lucasb-eyer** [comment]
There was a bit more to your suggestion than meets the eye: `vimba_camera_ptr_` isn't yet set at that point. Let me know when it's ready to merge and I'll squash the commits.

I don't know about the syncing yet; right now we're just looking at the two images in parallel (in Continuous mode), next step is to look into that. We don't have disparity/depth yet, and I've never done it before :smile:

**Comment by miquelmassot** [comment]
I didn't see that issue with the camera pointer. So I moved your lines after the camera opening, so that the pointer is already initialized. However, I had to get the interface type again.

**Pull request closed without merging**
