### PR TITLE
Dynamic reconfigure fix

### PR DESCRIPTION
**Pull request by shaun-edwards**
This change is required in `indigo`, but presumably is an issue in `kinetic` as well.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
This just failed on a different machine for me.  Closing this while I track it down.

**Comment by shaun-edwards** [comment]
I had the wrong file mode....it's now fixed.

**Comment by miquelmassot** [comment]
Thanks @shaun-edwards!

**Comment by shaun-edwards** [comment]
@miquelmassot, did you mean to close this without merging my change.  Just curious?

**Comment by shaun-edwards** [comment]
Friendly ping.

**Comment by miquelmassot** [comment]
Sorry @shaun-edwards, I forgot to merge it.

**Pull request merged**
